### ISSUE TITLE
Clarification on evaluate_fitness

### ISSUE THREAD

**Issue by palanik1** [vaughanlove/PromptBreeder#1]
@vaughanlove Thanks for putting out an initial version of the Prompt Breeder code.Super helpful!

I was looking at the evaluate_fitness function and had a quick question.

Do we need a unit = population.units[unit_index] before checking fitness scores at 
https://github.com/vaughanlove/PromptBreeder/blob/70374b6574e6c9178d4b57fea4d66b8b59424e6a/pb/__init__.py#L129

**Comment by vaughanlove** [comment]
you are absolutely right! good catch, I will fix that
